-- uy-jobs schema para Postgres directo (glyphium-postgres, DB uyjobs)
-- Derivado de supabase/schema.sql sin RLS (el backend usa acceso directo).
CREATE EXTENSION IF NOT EXISTS pg_trgm;

create table if not exists ofertas (
  id bigint generated by default as identity primary key,
  fuente text not null,
  oferta_id text,
  titulo text,
  empresa text,
  ubicacion text,
  salario text,
  contrato text,
  jornada text,
  fecha_publicacion text,
  url text unique not null,
  descripcion text,
  requisitos text,
  fecha_scrapeo timestamptz default now(),
  categoria text,
  tags text,
  modalidad text,
  seniority text,
  salario_num numeric,
  moneda text
);

create index if not exists idx_ofertas_fuente on ofertas (fuente);
create index if not exists idx_ofertas_categoria on ofertas (categoria);
create index if not exists idx_ofertas_modalidad on ofertas (modalidad);
create index if not exists idx_ofertas_titulo_trgm on ofertas using gin (titulo gin_trgm_ops);

ALTER TABLE ofertas OWNER TO uyjobs;
GRANT ALL PRIVILEGES ON TABLE ofertas TO uyjobs;
GRANT USAGE, SELECT ON SEQUENCE ofertas_id_seq TO uyjobs;
ALTER SEQUENCE ofertas_id_seq OWNED BY ofertas.id;

-- v2: departamento normalizado para filtros y mapa
alter table ofertas add column if not exists departamento text default '';
create index if not exists idx_ofertas_departamento on ofertas (departamento);

-- v3: años minimos de experiencia pedidos
alter table ofertas add column if not exists experiencia_min integer;
