-- uy-jobs: tabla de usuarios (login + registro + data mining)
create table if not exists users (
  id bigint generated by default as identity primary key,
  nombre text not null,
  email text unique not null,
  telefono text,
  password_hash text,
  google_id text unique,
  avatar_url text,
  departamento text,
  intereses text default '',
  created_at timestamptz default now()
);

create index if not exists idx_users_email on users (email);

ALTER TABLE users OWNER TO uyjobs;
GRANT ALL PRIVILEGES ON TABLE users TO uyjobs;
GRANT USAGE, SELECT ON SEQUENCE users_id_seq TO uyjobs;
