-- uy-jobs: engine semantico (perfiles CV + notificaciones de match)
create table if not exists profiles (
  user_id bigint primary key references users(id) on delete cascade,
  cv_text text default '',
  titulo text default '',
  skills text default '',
  experiencia text default '',
  updated_at timestamptz default now()
);

create table if not exists notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  oferta_id bigint not null references ofertas(id) on delete cascade,
  score int not null default 0,
  detail text default '',
  created_at timestamptz default now(),
  read_at timestamptz,
  unique(user_id, oferta_id)
);
create index if not exists idx_notif_user on notifications (user_id, created_at desc);

ALTER TABLE profiles OWNER TO uyjobs;
ALTER TABLE notifications OWNER TO uyjobs;
GRANT ALL PRIVILEGES ON TABLE profiles, notifications TO uyjobs;
GRANT USAGE, SELECT ON SEQUENCE notifications_id_seq TO uyjobs;

-- v2: guarda la llave del objeto CV en S3/MinIO
alter table profiles add column if not exists cv_file text default '';

-- v3: seguimiento de postulaciones del usuario
create table if not exists applications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  oferta_id bigint not null references ofertas(id) on delete cascade,
  status text not null default 'guardada'
    check (status in ('guardada','postulado','respuesta','entrevista','oferta','rechazado','descartado')),
  notes text default '',
  applied_at timestamptz,
  updated_at timestamptz default now(),
  unique(user_id, oferta_id)
);
create index if not exists idx_apps_user on applications (user_id, status);
ALTER TABLE applications OWNER TO uyjobs;
GRANT ALL PRIVILEGES ON TABLE applications TO uyjobs;
GRANT USAGE, SELECT ON SEQUENCE applications_id_seq TO uyjobs;

-- v4: marketing (marketingskills: analytics + referrals)
create table if not exists events (
  id bigint generated by default as identity primary key,
  event text not null,
  user_id bigint references users(id) on delete set null,
  path text default '',
  props jsonb default '{}',
  created_at timestamptz default now()
);
create index if not exists idx_events_event_time on events (event, created_at);
alter table users add column if not exists referral_code text unique;
alter table users add column if not exists referred_by bigint references users(id) on delete set null;
ALTER TABLE events OWNER TO uyjobs;
GRANT ALL PRIVILEGES ON TABLE events TO uyjobs;
GRANT USAGE, SELECT ON SEQUENCE events_id_seq TO uyjobs;

-- v5: ATS candidato (historial de cambios de estado)
create table if not exists application_events (
  id bigint generated by default as identity primary key,
  application_id bigint not null references applications(id) on delete cascade,
  from_status text default '',
  to_status text not null,
  created_at timestamptz default now()
);
create index if not exists idx_appevents_app on application_events (application_id, created_at desc);
ALTER TABLE application_events OWNER TO uyjobs;
GRANT ALL PRIVILEGES ON TABLE application_events TO uyjobs;
GRANT USAGE, SELECT ON SEQUENCE application_events_id_seq TO uyjobs;
